type StatData = {
	baseTalentScale?: string;
	additionalBonusTalentScale?: string;
	bonusTalentScale?: string;
	baseDEF?: string;
	additionalBonusDEF?: string;
	bonusDEF?: string;
	baseHP?: string;
	additionalBonusHP?: string;
	bonusHP?: string;
	baseEM?: string;
	additionalBonusEM?: string;
	bonusEM?: string;
	talent?: string;
	talentDEF?: string;
	talentHP?: string;
	talentEM?: string;
	talentDamageBonus?: string;
	talentDamageBonusDEF?: string;
	talentDamageBonusHP?: string;
	talentDamageBonusEM?: string;
	baseDamageMultiplier: string;
	flatDamage: string;
	damageBonus: string;
	em: string;
	characterLevel: string;
	reactionBonus: string;
	secondaryReactionBonus: string;
	critDamage: string;
	critRate: string;
	critDamageTransformative: string;
	critRateTransformative: string;
	enemyLevel: string;
	defenseIgnore: string;
	defenseDecrease: string;
	resistanceReduction: string;
	resistance: string;
	bowAimedTravelTime: string;
};

export default StatData;
