import StatValue from "../utils/StatValue";

type StatData = {
	baseTalentScale?: StatValue;
	additionalBonusTalentScale?: StatValue;
	bonusTalentScale?: StatValue;
	baseDEF?: StatValue;
	additionalBonusDEF?: StatValue;
	bonusDEF?: StatValue;
	baseHP?: StatValue;
	additionalBonusHP?: StatValue;
	bonusHP?: StatValue;
	baseEM?: StatValue;
	additionalBonusEM?: StatValue;
	bonusEM?: StatValue;
	talent?: StatValue;
	talentDEF?: StatValue;
	talentHP?: StatValue;
	talentEM?: StatValue;
	talentDamageBonus?: StatValue;
	talentDamageBonusDEF?: StatValue;
	talentDamageBonusHP?: StatValue;
	talentDamageBonusEM?: StatValue;
	talentScale: StatValue;
	baseDamageMultiplier: StatValue;
	flatDamage: StatValue;
	damageBonus: StatValue;
	em: StatValue;
	characterLevel: StatValue;
	reactionBonus: StatValue;
	critDamage: StatValue;
	critRate: StatValue;
	enemyLevel: StatValue;
	defenseIgnore: StatValue;
	defenseDecrease: StatValue;
	resistanceReduction: StatValue;
	resistance: StatValue;
};

export default StatData;
